# Generated by Django 5.2.12 on 2026-05-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_places', models.IntegerField(default=1)),
                ('code_unique', models.CharField(blank=True, max_length=10, unique=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de paiement'), ('paye', 'Payé et confirmé'), ('annule', 'Annulé'), ('expire', 'Expiré')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
